### ISSUE TITLE
Insert format

### ISSUE THREAD

**Issue by artbeglaryan** [shlima/click_house#1]
As I understand from ClickHouse logs, your driver inserts with JSONEachRow format, but the previous unmaintainable  one are inserting with CSVWithNames format. Is there a way to make this configurable or no?

I want to checkout to use your client, but need to modify bunch of things for that

**Comment by shlima** [comment]
Do you really need configurable option or will `CSVWithNames` suit everyone by default ?

**Comment by shlima** [comment]
I prefer `JSONEachRow` because of `CSVWithNames` requires non-standard serialization methods for inserted data

**Comment by artbeglaryan** [comment]
I have array of Strings like this

```
"'2019-10-01 11:00:00',10,90275,0,987654321,'USA','Clickhouse Application','',10,5,0,10.0,10.2,14.28"
```
and have separate column lists.
With older one I just split each row by `,` and pass it as a values for insert.

Right now if I split by `,` I have a array like this
```
["'2019-10-01 11:00:00'", "10", "90275", "0", "987654321", "'USA'", "'Clickhouse Application'", "''", "10", "5", "0", "10.0", "10.2", "14.28"]
```
 and on insert receive an error

```
2019.12.27 14:04:12.450596 [ 56 ] {cefcde41-df0e-4efd-86db-73dcc7a09d45} <Error> HTTPHandler: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected " before: \'2019-10-01 11:00:00\'","......
```
and as I understand problem is that client tries to insert `"'2019-10-01 11:00:00'"` for DateTime column, and I have no way to easy change incoming logic.

**Comment by shlima** [comment]
You have incorrect string serialization, please try to remove inner quotes from the strings:

```ruby
"'2019-10-01 11:00:00'"
```

Should be 

```ruby
"2019-10-01 11:00:00"
```

**Comment by shlima** [comment]
Waiting while Yandex fix the quotation with `CSV With Names`
