### ISSUE TITLE
Unable to Ping

### ISSUE THREAD

**Issue by epochslee** [shlima/click_house#10]
I know my setting are correct but I'm unable to ping. Do I need to set send_progress_in_http_headers to a certain value to get this to work?

2.3.8 :044 > require 'click_house'
 => false 
2.3.8 :045 > ClickHouse.config do |config|
2.3.8 :046 >       config.logger = Logger.new(STDOUT)
2.3.8 :047?>     config.adapter = :net_http
2.3.8 :048?>     config.database = 'default'
2.3.8 :049?>     config.timeout = 60
2.3.8 :050?>     config.open_timeout = 3
2.3.8 :051?>     config.ssl_verify = false
2.3.8 :052?>     config.headers = {}
2.3.8 :053?>     
2.3.8 :054 >       # or provide connection options separately
2.3.8 :055 >       config.scheme = 'http' 
2.3.8 :056?>     config.host = 'localhost' 
2.3.8 :057?>     config.port = '8123' 
2.3.8 :058?>     
2.3.8 :062?>   end
 => #<ClickHouse::Config:0x00007fbeb02571c0 @adapter=:net_http, @url=nil, @scheme="http", @host="localhost", @port="8123", @logger=#<Logger:0x00007fbeb0256798 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00007fbeb0256770 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007fbeb0256720 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007fbeb0256568>>>, @database="", @username="", @password="", @timeout=60, @open_timeout=3, @ssl_verify=false, @headers={}> 
2.3.8 :063 > ClickHouse.connection.ping
NoMethodError: undefined method `compact' for {:send_progress_in_http_headers=>nil, :database=>nil}:Hash
	from /Users/slee/.rvm/gems/ruby-2.3.8/gems/click_house-1.3.6/lib/click_house/connection.rb:49:in `compose'
	from /Users/slee/.rvm/gems/ruby-2.3.8/gems/click_house-1.3.6/lib/click_house/connection.rb:25:in `get'
	from /Users/slee/.rvm/gems/ruby-2.3.8/gems/click_house-1.3.6/lib/click_house/extend/connection_healthy.rb:8:in `ping'
	from (irb):63
	from /Users/slee/.rvm/rubies/ruby-2.3.8/bin/irb:11:in `<main>'

**Comment by shlima** [comment]
This gem requires [ruby version](https://ruby-doc.org/core-2.4.0/Hash.html#method-i-compact) at least 2.4.0, sorry  for the late response

I will specify minimal ruby version at the Gemfile
