### ISSUE TITLE
Inserting BigDecimal values

### ISSUE THREAD

**Issue by loadkpi** [shlima/click_house#11]
Hello, firstly thank you for the gem.

I have a parsing problem with inserting BigDecimal values to a table. The problem can be reproduced both for inserting BigDecimal type value and for manual casting:
```ruby
irb(main):003:0> c = ClickHouse.connection
irb(main):004:0> c.execute "CREATE TABLE test(id Decimal64(2)) ENGINE TinyLog"
irb(main):004:0> c.insert("test", columns: [:id], values: [[1.0]])
=> true

irb(main):006:0> c.insert("test", columns: [:id], values: [[BigDecimal("1.0")]])
ClickHouse::DbException ([400] Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected ',' before: '"0.1e1"}'{} (version 21.1.2.15 (official build)))
irb(main):007:0> c.insert("test", columns: [:id], values: [[ClickHouse::Type::DecimalType.new.serialize(1.0)]])
ClickHouse::DbException ([400] Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected ',' before: '"0.1e1"}'{} (version 21.1.2.15 (official build)))
```

As I understand this is due to 2 reasons:
1) Parsed BigDecimal value in Ruby represents as JSON String
2) Clichouse requires not to wrap in quotes numeric values while inserting to a table (using JSONEachRow format) 

Do you have any ideas to solve this?

**Comment by shlima** [comment]
Sorry for the late response, it seems to be that `BigDecimal.to_f` is the only right way to case Decimal to JSON correctly in Ruby,
