### ISSUE TITLE
Support for binary data

### ISSUE THREAD

**Issue by Ankk98** [shlima/click_house#20]
I can see that insert operations uses to_json which do not support non unicode data. But every other part of the system support binary data. Can we do something so that we do not need to replace invalid utf-8 chars using scrub?

DB support binary data
https://clickhouse.com/docs/en/sql-reference/data-types/string/#encodings

FORMAT supports binary data
http://www.devdoc.net/database/ClickhouseDocs_19.4.1.3-docs/interfaces/formats/#jsoneachrow

Gem uses to_json to convert hash(representing values of a row) to generate the query.
https://github.com/shlima/click_house/blob/588e65e63153e68a926aac961539fbca2a40a0fe/lib/click_house/extend/connection_inserting.rb#L18

But to_json does not work with binary data. It expects data to have valid unicode characters only.

There are many other formats also but I am not sure what format will solve this issue: https://clickhouse.com/docs/en/interfaces/formats/#jsoneachrow

```
[65] pry(main)> str = "\xc2"
=> "\xC2"
[66] pry(main)> Model.insert { |buffer| buffer << {:col1 => 1, :col2 => str} }
JSON::GeneratorError: partial character in source, but hit end
from /home/user/.rvm/gems/ruby-2.7.4/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'

[69] pry(main)> str.encoding
=> #<Encoding:UTF-8>
[70] pry(main)> str.valid_encoding?
=> false
```

I need to check how other db drivers support binary data.

I will be interested in contributing if needed and required.

Do you have ideas on how can we achieve this?

**Comment by shlima** [comment]
currently the developer has to keep an eye on the encoding  as I think
