### ISSUE TITLE
BigDecimal Type cast error

### ISSUE THREAD

**Issue by a747097587** [shlima/click_house#21]
ClickHouse.rb,  is `%d`

   ![深度截图_选择区域_20220111175031](https://user-images.githubusercontent.com/28568597/148922736-45d63658-20d5-4ab9-8962-c23b572da546.png)

ResultSet.rb , the output is `%s`
![深度截图_选择区域_20220111175110](https://user-images.githubusercontent.com/28568597/148922737-b12fcf88-c6d5-4e03-b9a2-e8b9c595e144.png)

Therefore the `BigDecimal` type will be treated as `undefined_type`

**Comment by shlima** [comment]
Current behaviour: 

```ruby
res = ClickHouse.connection.select_all 'SELECT toDecimal32(2, 4) AS x';
res.meta #=> {"name"=>"x", "type"=>"Decimal(9, 4)"}]
```

**Comment by a747097587** [comment]
@shlima 

The real type is still float

![深度截图_选择区域_20220124181248](https://user-images.githubusercontent.com/28568597/150764189-131f8e29-541c-473d-8192-7f3322322dc3.png)

The type becomes BigDecimal when I add `Decimal(%s, %s)`

![深度截图_选择区域_20220124181615](https://user-images.githubusercontent.com/28568597/150764447-3fa9f334-e104-46a5-8ed9-baec341e14cb.png)


![深度截图_选择区域_20220124181443](https://user-images.githubusercontent.com/28568597/150764239-1e47e576-c3f3-4493-952e-ca3c5a655979.png)
