### ISSUE TITLE
Guidance for adding `Lowcardinality` type

### ISSUE THREAD

**Issue by benschwarz** [shlima/click_house#36]
I'd like to use [`Lowcardinality`](https://clickhouse.com/docs/en/sql-reference/data-types/lowcardinality/), but as far as I can tell that isn't currently implemented in this library. 

I can contribute a patch to help implement this feature, but I wanted look for your guidance first. Do you have any recommendations for implementing this feature? It looks like the existing Array type might be a good starting place.

**Comment by shlima** [comment]
Added support in [DDL statement](https://github.com/shlima/click_house#create-table-using-dsl) in version `1.7.0`
