### ISSUE TITLE
Decimal type error

### ISSUE THREAD

**Issue by lireirelico** [shlima/click_house#39]
If change the precision value from 10 to > 17, the test will fail, this is not correct because the precision can go up to 76 (https://clickhouse.com/docs/en/sql-reference/data-types/decimal/#parameters)
https://github.com/shlima/click_house/blob/1282038c6dc712cdeb6a6114ec2e3f46b7212502/spec/click_house/type_spec.rb#L216

This is due to the fact that in BigDecimal when initializing Float, the maximum precision will be 17:
    If initial is a Float, and the digits is larger than Float::DIG + 1, this exception is raised.
    https://ruby-doc.org/stdlib-2.5.1/libdoc/bigdecimal/rdoc/BigDecimal.html#method-c-new-label-Exceptions

Can try converting the value to a string, but it is not clear whether precision works if pass a string:
https://github.com/shlima/click_house/blob/1282038c6dc712cdeb6a6114ec2e3f46b7212502/lib/click_house/type/decimal_type.rb#L7

**Comment by shlima** [comment]
Try to increase the limits:

```ruby
BigDecimal.limit(18)
```

**Comment by shlima** [comment]
Fixed in release `2.0.1`
