### ISSUE TITLE
How I to close connections with Socket

### ISSUE THREAD

**Issue by Kondzolko** [shlima/click_house#4]
Hello I have this error when I run 200 workers in one time,
"ActiveRecord::StatementInvalid: Errno::EMFILE: Failed to open TCP connection to 192.168.0.1:8123 (Too many open files - socket(2) for"

How I understand the problem is because I didn't close my old connection, can you tell me please if your gem has any method for closing connection with the socket?

Thank you.

**Comment by shlima** [comment]
@Kondzolko why your error says: **ActiveRecord::StatementInvalid** ?

**Comment by shlima** [comment]
You should try to use a [connection pool](https://github.com/shlima/click_house#using-with-a-connection-pool) or to choose another adapter, such as [NetHttpPersistent](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http_persistent.rb):

```ruby
ClickHouse.config do |config|
  config.adapter = :net_http_persistent
end
```

**Comment by Kondzolko** [comment]
Thank you very much @shlima, for your help, I replaced to config.adapter = :net_http_persistent and didn't see any more problems with TCP connection.
