### ISSUE TITLE
coerce nil and DateTime values in insert block

### ISSUE THREAD

**Issue by shved** [shlima/click_house#5]
Using "tuples" insert notation I noticed that if I attempt to write nil to it like this 
```
ClickHouse.connection.insert('devices', columns: %i(device_id kind model vendor os_name os_version referer updated_at created_at)) do |buf|
  buf << ['608253467_null', 'mobile', 'ALCATEL ONE TOUCH 993D', 'samsung', 'android', '19', nil, DateTime.parse('Sat, 13 Feb 2016 04:32:48').strftime('%Y-%m-%d %H:%M:%S'), DateTime.parse('Sat, 13 Feb 2016 03:39:07').strftime('%Y-%m-%d %H:%M:%S')]
end
```
(notice the nil value) raises exception `ClickHouse::DbException ([400] Code: 26, e.displayText() = DB::Exception: Cannot parse JSON string: expected opening quote: (while read the value of key referer): (at row 1))`

I assume that it would be better to silently convert value to its default value by column type on the fly ('' for String, 0 for Int and so on).

It is also surprising that time have to be specially formatted for clickhouse by hand as well. 

What do you think? Is it made to give more controll over data to user to avoid server versions compatibility issues?

**Comment by shved** [comment]
If you would agree that it is a good idea, I may work on a PR

**Comment by shved** [comment]
@shlima yo

**Comment by shlima** [comment]
@shved Did you try to create a table with `nullable` columns?

```ruby
ClickHouse.connection.create_table('devices') do |t|
  t.String :os_version, nullable: true
end
```

**Comment by shved** [comment]
Sorry, my bad!
