### ISSUE TITLE
Supporting ipv4/ipv6 types 

### ISSUE THREAD

**Issue by frostmark** [shlima/click_house#6]
Hi.
Noticed that now clickhouse supports Ipv4/Ipv6 https://clickhouse.tech/docs/en/sql-reference/data-types/domains/ipv4/.

I think would be nice to add that here.

Btw I can implement it in free time

**Comment by shlima** [comment]
@frostmark implemented in in v. `1.3.0`

**Comment by frostmark** [comment]
Thanks! 🙈
